"""refactor da userModel -> criando coluna reset_code

Revision ID: 4b6d94602b1c
Revises: 828c2d436429
Create Date: 2021-12-15 11:19:40.051298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6d94602b1c'
down_revision = '828c2d436429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
