"""Refactor table users.

Revision ID: 757360503f6c
Revises: 29c32b16b048
Create Date: 2021-12-09 17:05:18.202430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757360503f6c'
down_revision = '29c32b16b048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'type_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type_user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'verified')
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###
