"""create table captcha and refactor user table

Revision ID: 828c2d436429
Revises: 73b3e418c7b3
Create Date: 2021-12-14 15:24:57.494282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828c2d436429'
down_revision = '73b3e418c7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captchas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_captcha', sa.String(), nullable=False),
    sa.Column('captcha_content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captchas')
    # ### end Alembic commands ###
