"""update addresses table

Revision ID: a1086b311add
Revises: 12c0f569d555
Create Date: 2021-12-09 10:51:30.932635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1086b311add'
down_revision = '12c0f569d555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'user_id')
    # ### end Alembic commands ###
