"""Create table users

Revision ID: d68a0c3d8cc2
Revises: 727fec7a0fa7
Create Date: 2021-12-07 14:56:33.963036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68a0c3d8cc2'
down_revision = '727fec7a0fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('password_hash', sa.String(length=511), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('premium_at', sa.DateTime(), nullable=True),
    sa.Column('premium_expire', sa.DateTime(), nullable=True),
    sa.Column('type_user', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
